/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje1;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author USER
 */
public class girispaneli extends javax.swing.JFrame{

    /**
     * Creates new form girispaneli
     */
    public girispaneli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sekreterismi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sekreteralani = new javax.swing.JTextField();
        passwordalani = new javax.swing.JPasswordField();
        girisbutonu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GİRİSMENUSU");

        sekreterismi.setText("Kullanıcı");

        jLabel1.setText("Şifre:");

        sekreteralani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sekreteralaniActionPerformed(evt);
            }
        });

        girisbutonu.setText("Giris Yap");
        girisbutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisbutonuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("                         Randevu Sistemi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(girisbutonu)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sekreterismi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sekreteralani, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(passwordalani)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sekreterismi)
                    .addComponent(sekreteralani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(passwordalani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(girisbutonu)
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void girisbutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisbutonuActionPerformed
        // TODO add your handling code here:
        String bildirim;
        String ad=sekreteralani.getText();
        String sifre= passwordalani.getText();
        boolean kontrol=false;
         try{
        String host="jdbc:derby://localhost:1527/Veriy";//veritabanına bağlantı
        String name="sedat";
        String pass="123456";
        Connection con = DriverManager.getConnection(host, name, pass);
        Statement stmt = con.createStatement();
        String SQL = "SELECT * FROM UNTITLED";

        ResultSet rs = stmt.executeQuery( SQL );
        
        while(rs.next()){
        
         String adx=rs.getString("AD");
            String sifrex =rs.getString("SIFRE");
              
         ad=ad.replace(" ","");
         sifre=sifre.replace(" ","");
         adx=adx.replace(" ","");
         sifrex=sifrex.replace(" ","");
          
         if(sifrex.equals(sifre) && adx.equals(ad)){
             kontrol=true;
         }
          System.out.println(adx+" "+sifrex);
        
        }
        
         }
         catch(SQLException err){
                        System.out.println(err.getMessage());
        }
        
        
        if(kontrol){
            bildirim="GİRİŞ BAŞARILI.......";
            JOptionPane.showMessageDialog(this, bildirim);
            
             ögrencikayit b=new ögrencikayit();
            setVisible(false);
            b.setVisible(true);
            
        }
        else{
            bildirim="SIFRE HATALI ! Tekrar Deneyiniz";
            JOptionPane.showMessageDialog(this, bildirim);
        }
        
       
           
        
       // silme 1.txt
    }//GEN-LAST:event_girisbutonuActionPerformed

    private void sekreteralaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sekreteralaniActionPerformed
       
    }//GEN-LAST:event_sekreteralaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(girispaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(girispaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(girispaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(girispaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new girispaneli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton girisbutonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passwordalani;
    private javax.swing.JTextField sekreteralani;
    private javax.swing.JLabel sekreterismi;
    // End of variables declaration//GEN-END:variables
}
