package proje1;


import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MSI PC
 */
public class ögrencikayit extends javax.swing.JFrame {

     Queue sira;
    public ögrencikayit() {
        initComponents();
        
       sira=new Queue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        adkısmı = new javax.swing.JLabel();
        soyadkısmı = new javax.swing.JLabel();
        bölümkısmı = new javax.swing.JLabel();
        fakultekısmı = new javax.swing.JLabel();
        bolumadi = new javax.swing.JComboBox<String>();
        adsoyad = new javax.swing.JTextField();
        tc = new javax.swing.JTextField();
        yas = new javax.swing.JTextField();
        sikayet = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        yazdirmabutonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ögrenci Kayıt Sistemi");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Bölümler");

        adkısmı.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        adkısmı.setText("Hasta Adı-Soyadı");

        soyadkısmı.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        soyadkısmı.setText("TC");

        bölümkısmı.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bölümkısmı.setText("Yaş");

        fakultekısmı.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fakultekısmı.setText("Şikayet");

        bolumadi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dahiliye", "FTR", "KBB" }));
        bolumadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolumadiActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bölüm", "Ad Soyad", "TC", "Yaş", "Şikayet"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jButton1.setText("Hastayı Sıraya ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hasta işlemini tamamla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        yazdirmabutonu.setText("Eski kayıtları göster");
        yazdirmabutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yazdirmabutonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(adkısmı)
                            .addComponent(soyadkısmı)
                            .addComponent(bölümkısmı)
                            .addComponent(fakultekısmı))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bolumadi, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(134, 134, 134))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(sikayet, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(yas, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tc))
                                        .addGap(80, 80, 80)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yazdirmabutonu)))
                            .addComponent(adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 132, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bolumadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adkısmı)
                    .addComponent(adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soyadkısmı)
                    .addComponent(tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bölümkısmı)
                    .addComponent(yas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fakultekısmı)
                    .addComponent(sikayet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yazdirmabutonu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //hasta ekle bölümü
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String bildirim;
        DefaultTableModel model=(DefaultTableModel) table.getModel();
      //  baglan();
            if((adsoyad.getText().trim().equals(""))){
                bildirim="Ad boş bırakılamaz!";
                    JOptionPane.showMessageDialog(this, bildirim);//uyarı mesajı göndermek için kullanırız
            }
            else if(tc.getText().trim().equals("")){ 
                bildirim="Soyad boş bırakılamaz!";
                  JOptionPane.showMessageDialog(this, bildirim);
                
            }
            else if(yas.getText().trim().equals("")){
                bildirim="bölüm boş bırakılamaz!";
                  JOptionPane.showMessageDialog(this, bildirim);
            }
            else if(sikayet.getText().trim().equals("")){
                bildirim="fakulte boş bırakılamaz!";
                  JOptionPane.showMessageDialog(this, bildirim);
            }
            else {
                
                
              
Object [] dizi={bolumadi.getSelectedItem().toString(),adsoyad.getText(),tc.getText(),yas.getText(),sikayet.getText()};
    model.addRow(dizi);
    
    System.out.println("\n ******** \n");
   sira.EnQueue(bolumadi.getSelectedItem().toString(),adsoyad.getText(),tc.getText(),yas.getText(),sikayet.getText());
   
    sira.Show();// kod kontrol için
    
    
    yazdir(bolumadi.getSelectedItem().toString(),adsoyad.getText(),tc.getText(),yas.getText(),sikayet.getText());
    
     //ekle(adsoyad.getText(),tc.getText(),yas.getText(),sikayet.getText()); // bune anlamadım ????
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    // sıradaki hasta butonu  
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String bildirim;
    DefaultTableModel model=(DefaultTableModel)table.getModel();
        int satir=table.getSelectedRow();
            if(satir==-1){
                if(table.getRowCount()==0){
                    bildirim="Sırada Hasta bulunmuyor.";
                    JOptionPane.showMessageDialog(this, bildirim);
                }
               
            }
            sira.DeQueue();
            model.removeRow(satir);
                   bildirim="Seçili ögrencinin  kaydı başarıyla silindi.";
                   JOptionPane.showMessageDialog(this, bildirim);
                   adsoyad.setText("");
                   tc.setText("");
                   yas.setText("");
                   sikayet.setText("");
                   
                   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       DefaultTableModel model=(DefaultTableModel)table.getModel();
         int satir=table.getSelectedRow();
            bolumadi.setSelectedItem(model.getValueAt(satir, 0).toString());
            adsoyad.setText(model.getValueAt(satir, 1).toString());
            tc.setText(model.getValueAt(satir, 2).toString());
            yas.setText(model.getValueAt(satir, 3).toString());
            sikayet.setText(model.getValueAt(satir, 4).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void bolumadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolumadiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bolumadiActionPerformed

    private void yazdirmabutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yazdirmabutonuActionPerformed
        // TODO add your handling code here:
       //silme 5
        
    }//GEN-LAST:event_yazdirmabutonuActionPerformed

    //silme 4
   
   //silme 3
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ögrencikayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ögrencikayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ögrencikayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ögrencikayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ögrencikayit().setVisible(true);
            }
        });
    }
    
    public static void yazdir(String bölumadi,String adsoyad,String tc,String yas,String sikayet){
        
        Date now = new Date();
        
        
        File f=new File("kayit.txt");
        String kayit =now.toString()+" || "+bölumadi+" "+adsoyad+" "+ tc  +" "+ yas  +" "+sikayet;
        try {
            FileWriter fileWriter=new FileWriter(f,true);
            fileWriter.write(kayit);
            fileWriter.write("\n");
            fileWriter.close();
            
        }
        catch(IOException e){
            e.printStackTrace();
                } 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adkısmı;
    private javax.swing.JTextField adsoyad;
    private javax.swing.JComboBox<String> bolumadi;
    private javax.swing.JLabel bölümkısmı;
    private javax.swing.JLabel fakultekısmı;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sikayet;
    private javax.swing.JLabel soyadkısmı;
    private javax.swing.JTable table;
    private javax.swing.JTextField tc;
    private javax.swing.JTextField yas;
    private javax.swing.JButton yazdirmabutonu;
    // End of variables declaration//GEN-END:variables
}
