package proje1;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MSI PC
 */
public class ögrencikayit extends javax.swing.JFrame {

    /**
     * Creates new form KursOnKayit
     */
    public ögrencikayit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        adkısmı = new javax.swing.JLabel();
        soyadkısmı = new javax.swing.JLabel();
        bölümkısmı = new javax.swing.JLabel();
        fakultekısmı = new javax.swing.JLabel();
        bolumadi = new javax.swing.JComboBox<>();
        ad = new javax.swing.JTextField();
        soyad = new javax.swing.JTextField();
        bölüm = new javax.swing.JTextField();
        fakulte = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        yazdirmabutonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ögrenci Kayıt Sistemi");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Bölümler");

        adkısmı.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        adkısmı.setText("Hasta Adı-Soyadı");

        soyadkısmı.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        soyadkısmı.setText("TC");

        bölümkısmı.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bölümkısmı.setText("Yaş");

        fakultekısmı.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fakultekısmı.setText("Şikayet");

        bolumadi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dahiliye", "FTR", "KBB" }));
        bolumadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolumadiActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sınıf ", "Ad", "Soyad", "Bölüm", "Fakülte"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jButton1.setText("Kaydet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kayıt Sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Kayıt Güncelle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        yazdirmabutonu.setText("Eski kayıtları göster");
        yazdirmabutonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yazdirmabutonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(adkısmı)
                            .addComponent(soyadkısmı)
                            .addComponent(bölümkısmı)
                            .addComponent(fakultekısmı))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bolumadi, 0, 147, Short.MAX_VALUE)
                            .addComponent(ad)
                            .addComponent(soyad)
                            .addComponent(bölüm)
                            .addComponent(fakulte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(yazdirmabutonu))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(bolumadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adkısmı)
                            .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soyadkısmı)
                            .addComponent(soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bölümkısmı)
                            .addComponent(bölüm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fakultekısmı)
                            .addComponent(fakulte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(yazdirmabutonu, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String bildirim;
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        baglan();
            if((ad.getText().trim().equals(""))){
                bildirim="Ad boş bırakılamaz!";
                    JOptionPane.showMessageDialog(this, bildirim);//uyarı mesajı göndermek için kullanırız
            }
            else if(soyad.getText().trim().equals("")){ 
                bildirim="Soyad boş bırakılamaz!";
                  JOptionPane.showMessageDialog(this, bildirim);
                
            }
            else if(bölüm.getText().trim().equals("")){
                bildirim="bölüm boş bırakılamaz!";
                  JOptionPane.showMessageDialog(this, bildirim);
            }
            else if(fakulte.getText().trim().equals("")){
                bildirim="fakulte boş bırakılamaz!";
                  JOptionPane.showMessageDialog(this, bildirim);
            }
            else {
Object [] dizi={bolumadi.getSelectedItem().toString(),ad.getText(),soyad.getText(),bölüm.getText(),fakulte.getText()};
    model.addRow(dizi);
    System.out.println("MAHALELEE");
    ekle(ad.getText(),soyad.getText(),bölüm.getText(),fakulte.getText());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String bildirim;
    DefaultTableModel model=(DefaultTableModel)table.getModel();
        int satir=table.getSelectedRow();
            if(satir==-1){
                if(table.getRowCount()==0){
                    bildirim="Tablo'da ögrenci bulunmuyor.";
                    JOptionPane.showMessageDialog(this, bildirim);
                }
                else {
                    bildirim="Lütfen silmek istediğiniz satırı seçin";
                    JOptionPane.showMessageDialog(this, bildirim);
                }
            }
            model.removeRow(satir);
                   bildirim="Seçili ögrencinin  kaydı başarıyla silindi.";
                   JOptionPane.showMessageDialog(this, bildirim);
                   ad.setText("");
                   soyad.setText("");
                   bölüm.setText("");
                   fakulte.setText("");
                   
                   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       DefaultTableModel model=(DefaultTableModel)table.getModel();
         int satir=table.getSelectedRow();
            bolumadi.setSelectedItem(model.getValueAt(satir, 0).toString());
            ad.setText(model.getValueAt(satir, 1).toString());
            soyad.setText(model.getValueAt(satir, 2).toString());
            bölüm.setText(model.getValueAt(satir, 3).toString());
            fakulte.setText(model.getValueAt(satir, 4).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String bildirim;
       DefaultTableModel model=(DefaultTableModel)table.getModel();
        int satir=table.getSelectedRow();
            if(satir==-1){
                if(table.getRowCount()==0){
                bildirim="Tablo'da ögrenci bulunmuyor.";
                JOptionPane.showMessageDialog(this, bildirim);
                }
                else {
                bildirim="Lütfen güncelleme yapmak istediğiniz satırı seçiniz";
                JOptionPane.showMessageDialog(this, bildirim);
            }
           
            }
            else {
                model.setValueAt(ad.getText(), satir, 1);
                model.setValueAt(soyad.getText(), satir, 2);
                model.setValueAt(bölüm.getText(), satir, 3);
                model.setValueAt(fakulte.getText(), satir, 4);
                model.setValueAt(bolumadi.getSelectedItem().toString(), satir, 0);
                    bildirim="ögrenci kaydı başarıyla güncellendi.";
                    JOptionPane.showMessageDialog(this, bildirim);
                    
                    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bolumadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolumadiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bolumadiActionPerformed

    private void yazdirmabutonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yazdirmabutonuActionPerformed
        // TODO add your handling code here:
        String bildirim;
        yazdir(ad.getText(),soyad.getText(),bölüm.getText(),fakulte.getText());
        bildirim="dosya kayit.txt text dosyasina kaydedildi.";
                    JOptionPane.showMessageDialog(this, bildirim);
        
    }//GEN-LAST:event_yazdirmabutonuActionPerformed

    static ResultSet myRs;
    static Connection myConn;
    static Statement myStat;
    public static void baglan(){
        try
        {
            Connection veri = DriverManager.getConnection("jdbc:derby://localhost:1527/odevnyp","root","1234" );
            Statement stat=veri.createStatement();
            


        }
        catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, "Hata: " + ex.toString());
        }

    }
   
    public static void ekle(String ad,String soyad,String bolum,String fakulte){
        String sorgu="INSERT INTO odevnyp(adi,soyadi,bolumu,fakultesi) VALUES('"+ad+"','"+soyad+"','"+bolum+"','+"+fakulte+"')";
        try {
            Connection veri = DriverManager.getConnection("jdbc:derby://localhost:1527/odevnyp","root","1234" );
            Statement stat=veri.createStatement();
            stat.executeUpdate(sorgu);
            veri.close();
            JOptionPane.showMessageDialog(null,"başarılı");
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Hata: " + ex.toString());
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ögrencikayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ögrencikayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ögrencikayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ögrencikayit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ögrencikayit().setVisible(true);
            }
        });
    }
    
    public static void yazdir(String ad,String soyad,String bolum,String fakulte){
        File f=new File("kayit.text");
        String kayit =ad+soyad+bolum+fakulte;
        try {
            FileWriter fileWriter=new FileWriter(f,true);
            fileWriter.write(kayit);
            fileWriter.close();
            
        }
        catch(IOException e){
            e.printStackTrace();
                } 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JLabel adkısmı;
    private javax.swing.JComboBox<String> bolumadi;
    private javax.swing.JTextField bölüm;
    private javax.swing.JLabel bölümkısmı;
    private javax.swing.JTextField fakulte;
    private javax.swing.JLabel fakultekısmı;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField soyad;
    private javax.swing.JLabel soyadkısmı;
    private javax.swing.JTable table;
    private javax.swing.JButton yazdirmabutonu;
    // End of variables declaration//GEN-END:variables
}
